### ISSUE TITLE
No index.html being copied for River4 installs using S3 for storage

### ISSUE THREAD

**Issue by andysylvester** [scripting/river4#12]
Adam Monago commented on the River4 list that his River4 install using S3 did not save index.html to S3 storage. It appears that the calls to copyIndexFile in river4.js were removed in the first commit on 0.117. These calls should be restored so that River4 users using S3 storage will be able to publish a working River4 site using S3.

**Comment by scripting** [comment]
Hi Andy...

I'm working in a very distant part of my codebase right now and will not be able to investigate this now.

I do remember making this change because the index file it was writing was a terrible example of what's possible with River4. I think there are much more workable approaches.

Can you work around this, and provide an example for Adam for creating his own index file, using the examples I've provided, hopefully.

I think that's a much better way forward, at least for now.

**Comment by andysylvester** [comment]
Dave,

Thanks for responding, I will work with Adam to help him with his issue by creating a different index file based on your recent work.

Andy Sylvester
